/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_device_information             14
#define gattdb_manufacturer_name_string       16
#define gattdb_system_id                      18
#define gattdb_study_location                 19
#define gattdb_location_name_0                21
#define gattdb_server_characteristic_configuration 22
#define gattdb_space_occupied                 24
#define gattdb_ambient_light_measurement      26
#define gattdb_illuminance                    28
#define gattdb_microphone_control             30
#define gattdb_audio_input_description        32


#endif // __GATT_DB_H
